import React, { useState, useEffect } from 'react';
import axios from 'axios'; // Import Axios
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import './DeptHeadReportsPage.css';

const DeptHeadReportsPage = () => {
    
    // --- STATES ---
    const [selectedReportId, setSelectedReportId] = useState('FAC_SUMMARY');
    const [reportData, setReportData] = useState([]); // Holds DB data
    const [loading, setLoading] = useState(false);

    // --- REPORT CONFIGURATION ---
    const reportOptions = [
        // FACULTY REPORTS
        { id: 'FAC_SUMMARY', label: 'Faculty Attendance Summary', desc: 'Aggregates attendance and punctuality of instructors.', type: 'FACULTY', endpoint: '/reports/faculty-summary' },
        { id: 'FAC_LATE', label: 'Faculty Late Arrival Report', desc: 'Identifies recurring delays by faculty.', type: 'FACULTY', endpoint: '/reports/faculty-summary' }, // Reusing endpoint for now
        
        // ROOM REPORTS
        { id: 'ROOM_OCCUPANCY', label: 'Room Occupancy Trends', desc: 'Tracks occupants per room vs capacity.', type: 'ROOM', endpoint: '/reports/room-occupancy' },
        { id: 'OVERCROWDING', label: 'Overcrowding Alerts', desc: 'Detects rooms exceeding safety capacity.', type: 'ROOM', endpoint: '/reports/room-occupancy' }
    ];

    const currentReport = reportOptions.find(r => r.id === selectedReportId);
    const isRoomReport = currentReport?.type === 'ROOM';

    // --- FETCH DATA FROM DB ---
    useEffect(() => {
        const fetchData = async () => {
            setLoading(true);
            try {
                // Fetch from the specific endpoint defined in options
                const response = await axios.get(`http://localhost:5000${currentReport.endpoint}`);
                setReportData(response.data);
            } catch (error) {
                console.error("Error fetching report:", error);
                setReportData([]); // Fallback to empty if DB fails
            } finally {
                setLoading(false);
            }
        };

        if (currentReport?.endpoint) {
            fetchData();
        }
    }, [selectedReportId, currentReport]);

    // --- PDF GENERATOR ---
    const handleDownloadPDF = () => {
        const doc = new jsPDF();
        
        // Header Theme (Red)
        doc.setFillColor(166, 37, 37); 
        doc.rect(0, 0, 210, 40, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(18);
        doc.text("Department Management Report", 14, 20);
        doc.setFontSize(11);
        doc.text(currentReport.label, 14, 30);

        doc.setTextColor(50, 50, 50);
        doc.setFontSize(10);
        doc.text(`Generated By: Department Head`, 14, 50);
        doc.text(`Date: ${new Date().toLocaleString()}`, 14, 55);

        // Dynamic Columns based on DB Data
        let headers, body;

        if (isRoomReport) {
            headers = [["Room Name", "Capacity", "Peak Hour", "Utilization", "Status"]];
            body = reportData.map(r => [
                r.room_name, 
                r.capacity, 
                r.peak_hour, 
                r.utilization, 
                r.status
            ]);
        } else {
            headers = [["Faculty Name", "Subject Load", "Attendance", "Lates", "Remarks"]];
            body = reportData.map(f => [
                f.name, 
                f.subject_load, 
                f.attendance_rate, 
                f.lates, 
                f.remarks
            ]);
        }

        autoTable(doc, {
            head: headers,
            body: body,
            startY: 65,
            theme: 'grid',
            headStyles: { fillColor: [166, 37, 37] },
        });

        doc.save(`${currentReport.label.replace(/ /g, "_")}.pdf`);
    };

    return (
        <div className="dept-reports-container fade-in">
            <div className="dept-reports-header">
                <div className="dept-control-group">
                    <label>Select Report Type</label>
                    <select 
                        className="dept-select" 
                        value={selectedReportId}
                        onChange={(e) => setSelectedReportId(e.target.value)}
                    >
                        <optgroup label="Faculty Reports">
                            {reportOptions.filter(r => r.type === 'FACULTY').map(opt => (
                                <option key={opt.id} value={opt.id}>{opt.label}</option>
                            ))}
                        </optgroup>
                        <optgroup label="Facility Reports">
                            {reportOptions.filter(r => r.type === 'ROOM').map(opt => (
                                <option key={opt.id} value={opt.id}>{opt.label}</option>
                            ))}
                        </optgroup>
                    </select>
                </div>

                <div className="dept-report-info">
                    <i className={`fas ${isRoomReport ? 'fa-building' : 'fa-chalkboard-teacher'}`}></i>
                    <div className="info-content">
                        <h4>{currentReport.label}</h4>
                        <p>{currentReport.desc}</p>
                    </div>
                </div>
            </div>

            <div className="dept-table-card">
                <div className="dept-card-header">
                    <h3>Report Data {loading && <span style={{fontSize:'0.7em', color:'#888'}}>(Loading...)</span>}</h3>
                    <button className="btn-export" onClick={handleDownloadPDF} disabled={reportData.length === 0}>
                        <i className="fas fa-file-pdf"></i> Export PDF
                    </button>
                </div>

                <div className="dept-table-wrapper">
                    <table className="dept-table">
                        <thead>
                            {isRoomReport ? (
                                <tr>
                                    <th>Room Name</th>
                                    <th>Capacity</th>
                                    <th>Peak Hour</th>
                                    <th>Utilization</th>
                                    <th>Status</th>
                                </tr>
                            ) : (
                                <tr>
                                    <th>Faculty Name</th>
                                    <th>Subject Load</th>
                                    <th>Attendance %</th>
                                    <th>Lates</th>
                                    <th>Remarks</th>
                                </tr>
                            )}
                        </thead>
                        <tbody>
                            {reportData.length > 0 ? (
                                reportData.map((row, index) => (
                                    <tr key={index}>
                                        {isRoomReport ? (
                                            <>
                                                <td style={{fontWeight:'bold'}}>{row.room_name}</td>
                                                <td>{row.capacity}</td>
                                                <td>{row.peak_hour}</td>
                                                <td>
                                                    <span className={`status-pill ${parseInt(row.utilization) > 90 ? 'alert' : 'present'}`}>
                                                        {row.utilization}
                                                    </span>
                                                </td>
                                                <td>
                                                    <span className={`status-text ${row.status === 'Overcrowded' ? 'red-text' : 'green-text'}`}>
                                                        {row.status}
                                                    </span>
                                                </td>
                                            </>
                                        ) : (
                                            <>
                                                <td style={{fontWeight:'bold'}}>{row.name}</td>
                                                <td>{row.subject_load} Subjects</td>
                                                <td>{row.attendance_rate}</td>
                                                <td>
                                                    <span className={`status-pill ${row.lates > 3 ? 'late' : 'present'}`}>
                                                        {row.lates}
                                                    </span>
                                                </td>
                                                <td>{row.remarks}</td>
                                            </>
                                        )}
                                    </tr>
                                ))
                            ) : (
                                <tr>
                                    <td colSpan="5" style={{textAlign:'center', padding:'30px', color:'#888'}}>
                                        {loading ? "Fetching data..." : "No records found in database."}
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};

export default DeptHeadReportsPage;